### ISSUE TITLE
Example in README not working

### ISSUE THREAD

**Issue by triblix** [VictorDenisov/zendesk-api#1]
Hey @VictorDenisov im playing around with this library but havent grasped Conduits and Monad transformers yet.

I do not know if `listUsers` is missing or how to use it.

Thanks in advance!

**Comment by VictorDenisov** [comment]
I need to look into this. It's been sometime since I worked on it. Maybe it's outdated already. I'll let you know once I find this out.

**Comment by VictorDenisov** [comment]
@triblix The line you want to use is:

```
l <- rz $ getUsers $$ CL.consume
```

I'll update the readme file shortly.

**Comment by VictorDenisov** [comment]
Done.
